const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const report={checks:[],errors:[],screenshots:[]};
const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);console.log('PASS',name);};
(async()=>{
  const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
  const page=await browser.newPage({viewport:{width:1440,height:900}});
  page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
  fs.mkdirSync('art/qa',{recursive:true});
  const shot=async name=>{await page.waitForTimeout(180);await page.screenshot({path:`art/qa/${name}.png`});report.screenshots.push(name);};
  const place=async(x,y,z,yaw=0,pitch=0)=>page.evaluate(async({x,y,z,yaw,pitch})=>{const a=__afterlight;if(a.state.zone==='wasteland'){const A=await import('/src/archipelago.js');if(x===22&&z===-60.8){x=A.TOWNS[1].x+24;z=A.TOWNS[1].z+23.2;}else{x+=A.TOWNS[0].x;z+=A.TOWNS[0].z;}}a.world.player.position.set(x,y,z);a.state.position={x,y,z};a.state.field.yaw=yaw;a.state.field.pitch=pitch;a.world.velocityY=0;a.world.syncCamera(0);},{x,y,z,yaw,pitch});
  const move=async(key,frames)=>page.evaluate(async({key,frames})=>{for(let i=0;i<frames;i++)__afterlight.world.update(.05,i*.05,new Set([key]),false);const p={...__afterlight.state.position};if(__afterlight.state.zone==='wasteland'){const A=await import('/src/archipelago.js');p.x-=A.TOWNS[0].x;p.z-=A.TOWNS[0].z;}return p;},{key,frames});
  await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__afterlight?.world?.state);
  await page.getByRole('button',{name:'Enter Shelter 07',exact:false}).click();await page.waitForTimeout(300);
  check('start button enters active first-person play',await page.evaluate(()=>!__afterlight.paused&&__afterlight.world.camera.isPerspectiveCamera));
  await page.keyboard.down('KeyW');await page.waitForTimeout(400);await page.keyboard.up('KeyW');check('WASD changes the actual player position',await page.evaluate(()=>__afterlight.state.position.z<5.3));
  await page.mouse.move(790,430);await page.mouse.move(960,410);check('mouse look changes camera orientation',await page.evaluate(()=>Math.abs(__afterlight.state.field.yaw)>.01));
  await page.keyboard.press('KeyI');await page.getByRole('heading',{name:'Your backpack'}).waitFor();
  const minute=await page.evaluate(()=>__afterlight.state.minute);await page.waitForTimeout(250);check('opening the backpack pauses time',minute===await page.evaluate(()=>__afterlight.state.minute));
  await shot('inventory-home');await page.keyboard.press('Escape');await page.waitForTimeout(150);check('closing inventory resumes input',await page.evaluate(()=>!__afterlight.paused));
  await page.evaluate(()=>__afterlight.resumeForTest());
  await place(0,0,7.2,Math.PI,-.15);check('blast door has a physical interaction prompt',await page.evaluate(()=>__afterlight.world.nearest()?.id==='airlock'));
  await page.keyboard.press('KeyE');check('using the blast door enters the district',await page.evaluate(()=>__afterlight.state.zone==='wasteland'));
  check('archipelago has six abandoned settlements and active threats',await page.evaluate(()=>__afterlight.world.settlementBuildings.length===126&&__afterlight.world.enemies.length>=10));
  await page.evaluate(()=>{__afterlight.state.minute=16*60;__afterlight.world.enemies.forEach(e=>e.flee=1000);});await page.waitForTimeout(500);await shot('wasteland');
  await place(-24.2,0,49.7,0,-.15);const inside=await move('KeyW',48);check('walk through an actual shop entrance',inside.z<44);
  check('indoor cache is reachable by looking at it',await page.evaluate(()=>__afterlight.world.nearest()?.id==='market'));
  await shot('market-interior');const supplies=await page.evaluate(()=>__afterlight.actions.bagCount(__afterlight.state));
  await page.keyboard.press('KeyE');await page.waitForFunction(()=>__afterlight.task!==null);await page.waitForFunction(()=>!__afterlight.task,{timeout:10000});
  check('physical search adds supplies and exhausts the cache',await page.evaluate(n=>__afterlight.actions.bagCount(__afterlight.state)>n&&__afterlight.state.searched.market===__afterlight.state.day,supplies));
  await place(23,0,36.8);await move('KeyW',24);await move('KeyD',28);const upstairs=await move('KeyW',49);
  check('walk from street through doorway and climb 18 Blender stairs',upstairs.y>=3.55&&upstairs.z<25);
  await move('KeyA',32);await place(22.25,3.6,23.7,Math.PI,-.32);
  check('upstairs loot cannot be reached from the street but is reachable upstairs',await page.evaluate(()=>__afterlight.world.nearest()?.id==='wreck'));
  await shot('upstairs');
  await place(0,0,64,0,-.055);
  const combat=await page.evaluate(()=>{
    const a=__afterlight,w=a.world,s=a.state;w.enemies.forEach(e=>{e.dead=true;e.model.visible=false;});const e=w.enemies[0];e.dead=false;e.model.visible=true;e.health=70;e.model.position.set(w.player.position.x,0,w.player.position.z-10);e.flee=0;e.model.updateMatrixWorld(true);w.syncCamera(0);
    w.boxes.push({minX:w.player.position.x-2,maxX:w.player.position.x+2,minY:0,maxY:3,minZ:w.player.position.z-6,maxZ:w.player.position.z-5.6});w.cooldown=0;const blocked=w.shoot();const intact=e.health===70;w.boxes.pop();const hits=[];
    for(let i=0;i<3;i++){w.cooldown=0;w.syncCamera(0);hits.push(w.shoot());}
    return {blocked:!blocked.hit&&intact,hits,killed:e.dead,saved:s.field.defeated[e.id]===s.day,mag:s.field.weapons.pistol.mag};
  });
  check('solid cover blocks bullets',combat.blocked);check('aimed pistol shots damage and defeat a real enemy',combat.killed&&combat.hits.every(x=>x.hit));check('defeated enemies are persisted',combat.saved);check('each shot consumes a round',combat.mag===4);
  const reload=await page.evaluate(()=>{const a=__afterlight,w=a.world,gun=a.state.field.weapons.pistol,total=gun.mag+gun.reserve;w.beginReload();for(let i=0;i<40;i++)w.update(.05,i*.05,new Set(),false);return {mag:gun.mag,total:gun.mag+gun.reserve,before:total};});
  check('timed reload refills the magazine without creating ammo',reload.mag===8&&reload.total===reload.before);
  const cancelReload=await page.evaluate(()=>{const a=__afterlight;a.state.field.weapons.pistol.mag=2;const reserve=a.state.field.weapons.pistol.reserve;a.world.beginReload();a.actions.setWeapon(a.state,'pipe');a.world.equip('pipe');for(let i=0;i<40;i++)a.world.update(.05,i*.05,new Set(),false);const unchanged=a.state.field.weapons.pistol.mag===2&&a.state.field.weapons.pistol.reserve===reserve;const e=a.world.enemies[0];e.dead=false;e.model.visible=true;e.health=35;e.model.position.set(a.world.player.position.x,0,a.world.player.position.z-1.7);e.model.rotation.y=Math.PI;e.model.updateMatrixWorld(true);a.state.field.pitch=-.22;a.world.syncCamera(0);a.world.cooldown=0;const swing=a.world.shoot();return {unchanged,melee:swing.hit&&e.dead};});
  check('switching weapons cancels a reload without consuming ammunition',cancelReload.unchanged);check('the pipe can defeat an enemy at melee range',cancelReload.melee);
  await place(0,0,68,Math.PI,-.15);await page.keyboard.press('KeyE');check('walking back to shelter deposits the backpack',await page.evaluate(()=>__afterlight.state.zone==='shelter'&&__afterlight.actions.bagCount(__afterlight.state)===0));
  await page.evaluate(()=>{__afterlight.state.minute=12*60;__afterlight.state.health=100;});await place(7,0,-4.1,0,-.2);
  check('generator can be reached and serviced in person',await page.evaluate(()=>__afterlight.world.nearest()?.id==='generator'));
  const scrap=await page.evaluate(()=>__afterlight.state.resources.scrap);await page.keyboard.press('KeyE');await page.waitForFunction(()=>!!__afterlight.task);await page.keyboard.press('KeyD');
  check('moving cancels work without charging resources',await page.evaluate(n=>!__afterlight.task&&__afterlight.state.resources.scrap===n,scrap));
  await place(7,0,-4.1,0,-.2);await page.keyboard.press('KeyE');await page.waitForFunction(()=>!!__afterlight.task);await page.waitForFunction(()=>!__afterlight.task,{timeout:12000});
  check('completed base work changes supplies and records the daily duty',await page.evaluate(n=>__afterlight.state.field.jobs.generator===__afterlight.state.day&&__afterlight.state.resources.scrap===n-2,scrap));
  const crew=await page.evaluate(()=>{const a=__afterlight,w=a.world,start=w.npcs.map(n=>n.model.position.clone()),before=a.state.resources.scrap;for(let i=0;i<280;i++)w.updateNPCs(.25,i*.25);return {moved:w.npcs.some((n,i)=>n.model.position.distanceTo(start[i])>.5),worked:a.state.resources.scrap>before,status:w.npcs.map(n=>({name:n.person.name,task:n.status,position:n.model.position.toArray()}))};});
  check('NPCs walk between actual workstations',crew.moved);check('NPC shifts produce supplies',crew.worked);report.crew=crew.status;
  await place(0,0,5.5);await shot('shelter');
  await place(0,0,7.2,Math.PI,-.15);await page.keyboard.press('KeyE');await place(22,0,-60.8,0,-.55);
  check('checkpoint armoury is physically accessible',await page.evaluate(()=>__afterlight.world.nearest()?.id==='checkpoint'));
  await page.keyboard.press('KeyE');await page.waitForFunction(()=>!!__afterlight.task);await page.waitForFunction(()=>!__afterlight.task,{timeout:10000});
  await page.keyboard.press('Digit2');check('finding the checkpoint cache unlocks an equippable rifle',await page.evaluate(()=>__afterlight.state.field.equipped==='rifle'&&__afterlight.world.weaponId==='rifle'));
  const rifleMag=await page.evaluate(()=>__afterlight.state.field.weapons.rifle.mag);await page.mouse.move(720,450);await page.mouse.down();await page.waitForTimeout(450);await page.mouse.up();check('holding fire shoots successive rifle rounds',await page.evaluate(n=>__afterlight.state.field.weapons.rifle.mag<n-1,rifleMag));
  await place(0,0,36,0,0);
  for(const [weather,minute,name] of [['Fog',12*60,'fog'],['Radstorm',15*60,'radstorm'],['Clear skies',0,'night']]){
    await page.evaluate(({weather,minute})=>{const a=__afterlight;a.state.weather=weather;a.state.minute=minute;a.state.field.flashlight=true;a.world.enemies.forEach(e=>e.flee=1000);for(let i=0;i<8;i++)a.world.updateAtmosphere(.5,i);},{weather,minute});await page.waitForTimeout(200);await shot(name);
    check(`${name} changes world lighting or visibility`,await page.evaluate(name=>name==='night'?__afterlight.world.ambient.intensity<.4:__afterlight.world.scene.fog.density>.025,name));
  }
  await page.keyboard.press('KeyI');await shot('inventory');await page.keyboard.press('Escape');await page.evaluate(()=>__afterlight.resumeForTest());
  await page.keyboard.press('KeyH');await page.waitForTimeout(150);check('HUD can be completely hidden',await page.locator('#hud').evaluate(e=>e.classList.contains('hidden')));await page.keyboard.press('KeyH');
  const savedState=await page.evaluate(()=>{window.dispatchEvent(new Event('pagehide'));return {mag:__afterlight.state.field.weapons.rifle.mag,job:__afterlight.state.field.jobs.generator,zone:__afterlight.state.zone};});
  await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>__afterlight.world?.state);check('reload restores new weapons, daily tasks and world position',await page.evaluate(expected=>{const s=__afterlight.state;return s.field.weapons.rifle.owned&&s.field.weapons.rifle.mag===expected.mag&&s.field.jobs.generator===expected.job&&s.zone===expected.zone;},savedState));
  report.render=await page.evaluate(()=>({calls:__afterlight.world.renderer.info.render.calls,triangles:__afterlight.world.renderer.info.render.triangles,geometries:__afterlight.world.renderer.info.memory.geometries}));
  const mobile=await browser.newPage({viewport:{width:844,height:390},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>report.errors.push(e.message));await mobile.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});await mobile.waitForFunction(()=>__afterlight.world?.state);await mobile.getByRole('button',{name:'Enter Shelter 07',exact:false}).tap();await mobile.waitForTimeout(300);
  check('touch controls are available on a touch device',await mobile.locator('#touch-controls').evaluate(e=>getComputedStyle(e).display!=='none'));await mobile.getByRole('button',{name:'PACK',exact:true}).tap();check('inventory fits a small landscape screen',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.querySelector('.panel').getBoundingClientRect().height<=innerHeight));
  await mobile.screenshot({path:'art/qa/mobile-inventory.png'});report.screenshots.push('mobile-inventory');await mobile.close();
  check('no browser runtime or WebGL errors',report.errors.length===0);fs.writeFileSync('art/qa/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.checks.length,render:report.render,errors:report.errors}));await browser.close();
})().catch(e=>{console.error(e);fs.mkdirSync('art/qa',{recursive:true});fs.writeFileSync('art/qa/browser-report.json',JSON.stringify({...report,failure:String(e)},null,2));process.exit(1);});
