import * as A from './archipelago.js';
import {SHADY_SHORES} from './settlement.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const mapPosition=s=>s.zone==='shelter'?A.HOME:s.position;
export const distanceLabel=d=>d>=1000?`${(d/1000).toFixed(1)} km`:`${Math.round(d)} m`;
export function destinations(state,sites){return [{id:'home',name:'Shelter 07',...A.HOME},...A.TOWNS,SHADY_SHORES,...sites,...['bike','bike_extra'].filter(id=>state.field[id]).map(id=>({id,name:id==='bike_extra'?'Spare bicycle':'Parked bicycle',...state.field[id]})),...Object.entries(state.field.boats||{}).map(([id,boat])=>({id:`boat_${id}`,name:id==='holloway'?'Starry Sands boat':'Azure Port boat',...boat}))];}
export function localView(state){const [x,z]=A.imagePoint(mapPosition(state)),width=240/A.MAP_SCALE,height=180/A.MAP_SCALE;return [x-width/2,z-height/2,width,height];}
export function coastalMap(state,sites,available,{local=false,buildings=[],interactive=false}={}){
  const points=p=>p.map(v=>A.imagePoint(v).join(',')).join(' ');
  const pos=mapPosition(state),player=A.imagePoint(pos),home=A.imagePoint(A.HOME),view=local?localView(state):[0,0,1448,1086];
  const unit=local?.18:1, font=local?5.3:23;
  const text=(x,y,value,color='#fff2d5',size=font)=>`<text x="${x}" y="${y}" text-anchor="middle" fill="${color}" stroke="#253027" stroke-width="${unit*3}" paint-order="stroke" font-size="${size}" font-family="sans-serif">${esc(value)}</text>`;
  const marker=(p,label,color,id,shape='circle')=>{const [x,y]=A.imagePoint(p);return `<g ${interactive?`data-destination="${esc(id)}" role="button" tabindex="0" aria-label="Set destination: ${esc(label)}"`:''}><title>${esc(label)}</title><circle cx="${x}" cy="${y}" r="${unit*17}" fill="transparent"/>${shape==='circle'?`<circle cx="${x}" cy="${y}" r="${unit*7}" fill="${color}" stroke="#172322" stroke-width="${unit*2}"/>`:`<path d="M${x} ${y-unit*10}l${unit*10} ${unit*10}l${-unit*10} ${unit*10}l${-unit*10} ${-unit*10}z" fill="${color}"/>`}${text(x,y+(id==='bike'?-font:font*1.4),label,color)}</g>`;};
  const wp=state.field.waypoint, end=wp?A.imagePoint(wp):null;
  let waypoint='';
  if(end){const dx=end[0]-player[0],dy=end[1]-player[1],edge=local?Math.max(1,Math.abs(dx)/(view[2]*.40),Math.abs(dy)/(view[3]*.34)):1,ex=player[0]+dx/edge,ey=player[1]+dy/edge;
    waypoint=`<path d="M${player.join(' ')}L${end.join(' ')}" fill="none" stroke="#f2ad67" stroke-width="${unit*2}" stroke-dasharray="${unit*8} ${unit*6}"/><circle cx="${ex}" cy="${ey}" r="${unit*10}" fill="none" stroke="#ffbc7d" stroke-width="${unit*3}"/>${text(ex,ey-font, distanceLabel(Math.hypot(wp.x-pos.x,wp.z-pos.z)),'#ffce97')}`;
  }
  const [vx,vy,vw,vh]=view,scale=local?50:500;
  return `<svg class="field-map ${local?'local-map':''}" viewBox="${view.join(' ')}" preserveAspectRatio="xMidYMid meet" aria-label="${local?'Nearby area: 240 metres across, north up':'Coastal archipelago map'}"><rect x="${vx}" y="${vy}" width="${vw}" height="${vh}" fill="#253f46"/>${A.ISLANDS.map(p=>`<polygon points="${points(p)}" fill="#69705a" stroke="#b4aa88" stroke-width="${local?1:5}"/>`).join('')}<g fill="none" stroke="#c1b08a" stroke-width="${local?2:5}" stroke-linejoin="round">${A.ROADS.map(p=>`<polyline points="${points(p)}"/>`).join('')}</g><g fill="none" stroke="#c3c4b2" stroke-width="${local?3:8}">${[...A.BRIDGES,...A.DOCKS].map(p=>`<polyline points="${points(p)}"/>`).join('')}</g>${buildings.filter(b=>!local||Math.hypot(b.x-pos.x,b.z-pos.z)<180).map(b=>{const [x,y]=A.imagePoint(b);return `<rect x="${x-3}" y="${y-3}" width="6" height="6" fill="#414b3d" stroke="#a4a68a" stroke-width=".5"/>`;}).join('')}${A.TOWNS.map(t=>marker(t,t.name,'#eee1bd',t.id)).join('')}${sites.map((s,i)=>marker(s,local?String(i+1):`${i+1}`,available(s.id)?'#f1cc76':'#999d96',s.id,'diamond')).join('')}${marker(A.HOME,'SHELTER 07','#a8d7b9','home','diamond')}${marker(SHADY_SHORES,local?'TOWN':'SHADY SHORES','#e8bb7f','shady_shores','diamond')}${state.field.bike?marker(state.field.bike,local?'BIKE':'BICYCLE','#88d6e5','bike','diamond'):''}${state.field.bike_extra?marker(state.field.bike_extra,local?'BIKE':'SPARE BIKE','#9bd7ac','bike_extra','diamond'):''}${Object.entries(state.field.boats||{}).map(([id,boat])=>marker(boat,local?'BOAT':'BOAT','#8fdef1',`boat_${id}`,'diamond')).join('')}${waypoint}<g transform="translate(${player.join(' ')}) rotate(${-state.field.yaw*180/Math.PI})"><path d="M0 ${-unit*26}L${-unit*17} ${-unit*2}L${unit*17} ${-unit*2}Z" fill="#fff9d9" opacity=".22"/><path d="M0 ${-unit*13}L${-unit*7} ${unit*9}L0 ${unit*5}L${unit*7} ${unit*9}Z" fill="#fff9d9" stroke="#172322" stroke-width="${unit*2}"/></g>${text(vx+vw-unit*30,vy+unit*32,'N ↑','#eadcbd')}<path d="M${vx+unit*20} ${vy+vh-unit*32}h${scale/A.MAP_SCALE}" stroke="#eadcbd" stroke-width="${unit*2}"/>${text(vx+unit*20+scale/A.MAP_SCALE/2,vy+vh-unit*12,`${scale} m`,'#eadcbd',font*.75)}</svg>`;
}
