import * as G from './state.js';
import {MAIL,KIT_LIMITS} from './computer.js';
import {coastalMap,destinations,mapPosition,distanceLabel} from './coastal-map.js';
import * as H from './shelter.js';
import {renderStarrySandsComputer} from './town-computer-ui.js';

const safe=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const APPS={desktop:'Desktop',inventory:'Inventory',calendar:'Calendar',weather:'Weather',mail:'Email',map:'Map',shelter:'Shelter',people:'People',town:'Starry Sands'};
const svg=shapes=>`<svg viewBox="0 0 32 32" shape-rendering="crispEdges" aria-hidden="true">${shapes}</svg>`;
const ICONS={
  inventory:svg('<path fill="#665330" d="M2 10h28v17H2z"/><path fill="#f4d477" d="M2 8h11l3 3h14v15H2z"/><path fill="#fff1ae" d="M4 10h25v3H4z"/>'),
  calendar:svg('<path fill="#777" d="M4 5h25v26H4z"/><path fill="#fff" d="M3 4h25v25H3z"/><path fill="#000080" d="M3 4h25v6H3z"/><path fill="#ed7559" d="M8 2h3v6H8zm12 0h3v6h-3z"/><path fill="#777" d="M7 14h4v3H7zm7 0h4v3h-4zm7 0h4v3h-4zM7 20h4v3H7zm7 0h4v3h-4zm7 0h4v3h-4z"/>'),
  weather:svg('<path fill="#ffd659" d="M17 2h3v5h-3zM4 14h5v3H4zm21 0h5v3h-5zM8 5l3-2 3 4-3 2zm15 1 3 2-3 3-3-2z"/><circle fill="#f7c641" cx="18" cy="16" r="7"/><path fill="#fff" d="M5 23h4v-4h5v-3h8v4h5v3h3v6H5z"/><path fill="#9a9a9a" d="M5 27h25v3H5z"/>'),
  mail:svg('<path fill="#555" d="M2 7h29v22H2z"/><path fill="#fff" d="M2 5h28v22H2z"/><path fill="#d8d8d8" d="m2 7 14 11L30 7v4L16 22 2 11z"/><path fill="#000080" d="M2 5h28v3H2z"/>'),
  map:svg('<path fill="#777" d="M3 7 12 4l9 3 8-3v22l-8 3-9-3-9 3z"/><path fill="#eee7be" d="m4 8 8-3v20l-8 3zm9-3 8 3v20l-8-3zm9 3 6-3v20l-6 3z"/><path stroke="#399784" stroke-width="2" fill="none" d="m5 21 8-6 6 4 8-8"/>'),
  shelter:svg('<path fill="#595959" d="M3 7h26v23H3z"/><path fill="#a7b8c7" d="M4 4h24v23H4z"/><path fill="#000080" d="M4 4h24v5H4z"/><path fill="#fff" d="M8 12h16v2H8zm0 5h12v2H8zm0 5h16v2H8z"/><path fill="#e4c36c" d="M22 16h3v5h-3z"/>'),
  people:svg('<path fill="#5477b0" d="M4 20h11v9H4zm14 0h11v9H18z"/><path fill="#f0c69e" d="M6 7h8v10H6zm12 0h8v10h-8z"/><path fill="#765b46" d="M5 5h10v5H5zm12 0h10v5H17z"/><path fill="#fff" d="M8 11h2v2H8zm12 0h2v2h-2z"/>'),
  town:svg('<path fill="#555" d="M2 16 16 3l14 13v14H2z"/><path fill="#c7b28a" d="M3 16 16 4l13 12v13H3z"/><path fill="#8f3933" d="M1 16 16 2l15 14-2 3-13-12L3 19z"/><path fill="#486975" d="M12 19h8v10h-8z"/><path fill="#e5d79c" d="M5 20h5v5H5zm17 0h5v5h-5z"/>'),
};
const number=value=>String(value).padStart(2,'0');
function inventory(state){
  const kit=state.computer.kit;
  return `<div class="pc-inventory"><p>Prepare the supplies to pack automatically when leaving Shelter 07.</p><div class="pc-inventory-head"><b>Item</b><b>Stockpile</b><b>Field kit</b></div>${G.RESOURCE_KEYS.map(key=>`<div class="pc-inventory-row"><span>${safe(G.RESOURCE_NAMES[key])}</span><strong>${state.resources[key]}</strong><span>${Object.hasOwn(KIT_LIMITS,key)?`<button data-action="pc-kit" data-id="${key}" data-delta="-1" ${kit[key]===0?'disabled':''}>−</button><b>${kit[key]}</b><button data-action="pc-kit" data-id="${key}" data-delta="1" ${kit[key]>=KIT_LIMITS[key]?'disabled':''}>+</button>`:'Stockpile only'}</span></div>`).join('')}<p class="pc-note">Prepared: ${Object.values(kit).reduce((n,v)=>n+v,0)} / ${G.bagCapacity(state)} slots. Your backpack is filled from the stockpile at departure.</p><p class="pc-note">Food: ${Math.floor(state.resources.food/Math.max(1,state.residents.length))} days · Water: ${Math.floor(state.resources.water/Math.max(1,state.residents.length*2))} days at current population.</p></div>`;
}
function calendar(state){
  const month=Math.floor((state.day-1)/28)+1,today=(state.day-1)%28+1,start=(month-1)*28;
  const days=Array.from({length:28},(_,i)=>`<div class="${i+1===today?'today':''}"><strong>${i+1}</strong>${i+1===today?'<small>Today</small>':''}</div>`).join('');
  const notes=state.log.filter(entry=>entry.day>=start+1&&entry.day<=start+28).slice(0,6);
  return `<div class="pc-calendar"><h3>Cycle ${month} · Day ${state.day}</h3><div class="pc-calendar-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=>`<b>${day}</b>`).join('')}${days}</div><h4>Recent shelter entries</h4><ul>${notes.length?notes.map(entry=>`<li><b>Day ${entry.day}</b> ${safe(entry.text)}</li>`).join(''):'<li>No entries this cycle.</li>'}</ul></div>`;
}
function weather(state){
  const condition=state.weather,storm=condition==='Radstorm',fog=condition==='Fog',risk=storm?'HIGH':fog?'MODERATE':'LOW';
  return `<div class="pc-weather"><div class="pc-weather-current"><span>${storm?'☢':fog?'≋':condition==='Dust haze'?'◌':'☀'}</span><div><small>OUTSIDE SHELTER 07</small><h3>${safe(condition)}</h3><p>Day ${state.day} · ${number(Math.floor(state.minute/60))}:${number(Math.floor(state.minute%60))}</p></div></div><div class="pc-weather-grid"><article><b>${risk}</b><span>Exposure risk</span></article><article><b>${Math.round(state.radiation)}%</b><span>Personal radiation</span></article><article><b>${Math.round(state.integrity)}%</b><span>Shelter condition</span></article></div><p class="pc-note">This station reports current conditions. Future weather may change overnight.</p></div>`;
}
function mail(state,open){
  const items=[...state.computer.mail].map((message,index)=>({...message,index})).reverse();
  const message=Number.isInteger(open)?state.computer.mail[open]:null,template=message&&MAIL[message.template];
  return `<div class="pc-mail"><aside><h3>Inbox (${items.filter(m=>!m.read).length} unread)</h3>${items.length?items.map(item=>{const letter=MAIL[item.template];return `<button class="${item.read?'':'unread'} ${item.index===open?'selected':''}" data-action="pc-mail-open" data-id="${item.index}"><b>${safe(letter.from)}</b><span>${safe(letter.subject)}</span><small>Day ${item.day}</small></button>`;}).join(''):'<p>No messages yet. Each new day has a 25% chance of receiving one.</p>'}</aside><article>${template?`<small>FROM: ${safe(template.from)} · DAY ${message.day}</small><h3>${safe(template.subject)}</h3><p>${safe(template.body)}</p>`:'<p>Select a message to read it. The terminal checks for new mail each morning.</p>'}</article></div>`;
}
function map(state,world){
  const places=destinations(state,G.SITES),pos=mapPosition(state);
  return `<div class="pc-map"><div class="pc-map-image">${coastalMap(state,G.SITES,id=>G.siteAvailable(state,id),{local:false,interactive:false,buildings:world?.settlementBuildings||[]})}</div><div class="pc-places"><h3>Places</h3>${places.map(place=>`<button data-action="pc-place" data-id="${safe(place.id)}"><b>${safe(place.name)}</b><small>${distanceLabel(Math.hypot(place.x-pos.x,place.z-pos.z))}${G.SITES.some(site=>site.id===place.id)?G.siteAvailable(state,place.id)?' · supplies available':` · restocks day ${state.searched[place.id]+3}`:''}</small></button>`).join('')}</div></div>`;
}
function shelter(state,floor,slot){
  const selectedFloor=Math.max(1,Math.min(state.shelter.floors,floor||1)),selected=Number.isInteger(slot)?slot:null,room=selected===null?null:H.roomAt(state,selectedFloor,selected);
  const options=selected===null?'<p>Select a room bay to manage it.</p>':room?`<h4>${safe(H.ROOMS[room.id].name)} · Level ${room.level}</h4><p>${safe(H.ROOMS[room.id].detail)}</p>`:`<h4>Add a room here · Floor ${selectedFloor}</h4><div class="pc-room-options">${Object.entries(H.ROOMS).map(([id,spec])=>{const locked=id==='computer'&&selectedFloor<2||id==='reactor'&&selectedFloor<8,cost=H.roomCost(state,id,selectedFloor,selected);return `<button data-action="pc-build-room" data-id="${id}" data-floor="${selectedFloor}" data-slot="${selected}" ${locked||!G.canAfford(state,cost)?'disabled':''}><b>${safe(spec.name)}</b><small>${locked?'Floor restricted':Object.entries(cost).map(([key,n])=>`${n} ${G.RESOURCE_NAMES[key]}`).join(' + ')}</small></button>`;}).join('')}</div>`;
  return `<div class="pc-shelter"><p>Build and manage rooms on the selected floor. ${state.resources.scrap} scrap in stock.</p><div class="pc-floor-tabs">${Array.from({length:state.shelter.floors},(_,i)=>`<button data-action="pc-floor" data-floor="${i+1}" class="${selectedFloor===i+1?'selected':''}">Floor ${i+1}</button>`).join('')}</div><div class="pc-bays">${H.SLOTS.map((bay,index)=>{const placed=H.roomAt(state,selectedFloor,index);return `<button data-action="pc-room-slot" data-floor="${selectedFloor}" data-slot="${index}" class="${selected===index?'selected':''}"><b>${safe(bay.name)}</b><small>${placed?safe(H.ROOMS[placed.id].name):'Empty · add room'}</small></button>`;}).join('')}</div><div class="pc-room-editor">${options}</div><p class="pc-note">Add another floor from the expansion plans in the radio room.</p></div>`;
}
function people(state,selected){
  const residents=state.residents.slice(1),person=residents.find(item=>item.name===selected)||residents[0],assignment=person&&state.shelter.assignments?.[person.name],rooms=H.placements(state).filter(place=>place.room.id!=='bedrooms');
  return `<div class="pc-people"><aside><h3>Residents</h3>${residents.map(item=>`<button data-action="pc-person" data-id="${safe(item.name)}" class="${item.name===person?.name?'selected':''}"><b>${safe(item.name)}</b><small>${safe(item.role)}</small></button>`).join('')}</aside><section>${person?`<h3>${safe(person.name)} · ${safe(person.role)}</h3><p>${safe(person.benefit)}</p><p>Work room: <b>${assignment?`${safe(H.ROOMS[H.roomAt(state,assignment.floor,assignment.slot)?.id]?.name||'Unavailable')} · Floor ${assignment.floor}, ${safe(H.SLOTS[assignment.slot]?.name||'')}`:'Automatic assignment'}</b></p><div class="pc-workrooms"><button data-action="pc-assign" data-name="${safe(person.name)}" data-floor="auto" class="${assignment?'':'selected'}">Automatic assignment</button>${rooms.map(place=>`<button data-action="pc-assign" data-name="${safe(person.name)}" data-floor="${place.floor}" data-slot="${place.slot}" class="${assignment?.floor===place.floor&&assignment?.slot===place.slot?'selected':''}">${safe(H.ROOMS[place.room.id].name)} · Floor ${place.floor} · ${safe(H.SLOTS[place.slot].name)}</button>`).join('')}</div>`:'<p>No other residents yet. The radio can invite survivors.</p>'}</section></div>`;
}
export function renderComputer(state,app='desktop',open=null,world=null,floor=1,slot=null,person=null,townTab='overview',townSelection=null){
  const active=Object.hasOwn(APPS,app)?app:'desktop',unread=state.computer.mail.filter(item=>!item.read).length;
  const content=active==='desktop'?`<div class="pc-icons">${Object.keys(ICONS).map(key=>`<button data-action="pc-app" data-id="${key}"><span class="pc-icon">${ICONS[key]}</span>${APPS[key]}${key==='mail'&&unread?` <b>(${unread})</b>`:''}</button>`).join('')}</div><div class="pc-welcome">Shelter 07<br><small>Communications terminal · Day ${state.day}</small></div>`:active==='inventory'?inventory(state):active==='calendar'?calendar(state):active==='weather'?weather(state):active==='mail'?mail(state,open):active==='map'?map(state,world):active==='shelter'?shelter(state,floor,slot):active==='town'?renderStarrySandsComputer(state,townTab,townSelection):people(state,person);
  return `<div class="pc-desktop"><div class="pc-wallpaper">${active==='desktop'?'':`<div class="pc-window"><div class="pc-title"><span>▣ ${APPS[active]} - Shelter 07</span><button data-action="pc-app" data-id="desktop" aria-label="Close app">×</button></div><div class="pc-window-body">${content}</div></div>`}${active==='desktop'?content:''}</div><div class="pc-taskbar"><button data-action="pc-app" data-id="desktop"><b>▦</b> Start</button><span>${active==='desktop'?'Shelter 07':APPS[active]}</span><time>Day ${state.day} · ${number(Math.floor(state.minute/60))}:${number(Math.floor(state.minute%60))}</time></div></div>`;
}
